baseURL = 'https://bbbberd.github.io/'
locale = 'id-id'
title = 'Birdie'
theme = 'PaperMod'

[pagination]
pagerSize = 5

[params]
defaultTheme = 'dark'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3